// Generated by @wagmi/cli@1.0.0 on 18/05/2023 at 19:23:33
import {
  useContractRead,
  UseContractReadConfig,
  useContractWrite,
  UseContractWriteConfig,
  usePrepareContractWrite,
  UsePrepareContractWriteConfig,
  useContractEvent,
  UseContractEventConfig
} from 'wagmi'
import {
  ReadContractResult,
  WriteContractMode,
  PrepareWriteContractResult
} from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Database
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const databaseABI = [
  { stateMutability: 'nonpayable', type: 'constructor', inputs: [] },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'collectionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'organisationId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false
      },
      {
        name: 'collectionName',
        internalType: 'string',
        type: 'string',
        indexed: false
      },
      {
        name: 'collectionInfoFields',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'collectionInfoDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false
      },
      {
        name: 'collectionInfoValues',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'fieldNames',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'fieldDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: false
      }
    ],
    name: 'CollectionCreated'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'collectionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'organisationId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'collectionName',
        internalType: 'string',
        type: 'string',
        indexed: false
      },
      {
        name: 'collectionInfoFields',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'collectionInfoDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false
      },
      {
        name: 'collectionInfoValues',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'fieldNames',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'fieldDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: false
      },
      { name: 'retired', internalType: 'bool', type: 'bool', indexed: false }
    ],
    name: 'CollectionUpdated'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'documentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'organisationId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'collectionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'fieldNames',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'fieldDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false
      },
      {
        name: 'fieldValues',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: false
      }
    ],
    name: 'DocumentPublished'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'collectionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'documentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'organisationId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'fieldNames',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'fieldDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false
      },
      {
        name: 'fieldValues',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: false
      },
      { name: 'retired', internalType: 'bool', type: 'bool', indexed: false }
    ],
    name: 'DocumentUpdated'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'newFeeCollectorAddress',
        internalType: 'address',
        type: 'address',
        indexed: true
      }
    ],
    name: 'FeeCollectorAddressUpdated'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'organisationId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'organisationName',
        internalType: 'string',
        type: 'string',
        indexed: false
      },
      {
        name: 'organisationInfoFields',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'organisationInfoDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false
      },
      {
        name: 'organisationInfoValues',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      }
    ],
    name: 'OrganisationCreated'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'organisationId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'organisationName',
        internalType: 'string',
        type: 'string',
        indexed: false
      },
      {
        name: 'organisationInfoFields',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      {
        name: 'organisationInfoDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]',
        indexed: false
      },
      {
        name: 'organisationInfoValues',
        internalType: 'string[]',
        type: 'string[]',
        indexed: false
      },
      { name: 'retired', internalType: 'bool', type: 'bool', indexed: false }
    ],
    name: 'OrganisationUpdated'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true
      }
    ],
    name: 'OwnershipTransferred'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'newCreationFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      }
    ],
    name: 'collectionCreationFeeChanged'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'organisationId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'collectionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'status', internalType: 'bool', type: 'bool', indexed: false }
    ],
    name: 'collectionPublisherChanged'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'newUpdateFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      }
    ],
    name: 'collectionUpdateFeeChanged'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'newCreationFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      }
    ],
    name: 'documentCreationFeeChanged'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'newUpdateFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      }
    ],
    name: 'documentUpdateFeeChanged'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'organisationId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'collectionId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'documentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      {
        name: 'user',
        internalType: 'address',
        type: 'address',
        indexed: false
      },
      { name: 'status', internalType: 'bool', type: 'bool', indexed: false }
    ],
    name: 'documentUpdatorChanged'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'organisationId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      },
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'status', internalType: 'bool', type: 'bool', indexed: false }
    ],
    name: 'orgAdminChanged'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'newCreationFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      }
    ],
    name: 'orgCreationFeeChanged'
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'newUpdateFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true
      }
    ],
    name: 'orgUpdateFeeChanged'
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_creationFee', internalType: 'uint256', type: 'uint256' }
    ],
    name: 'changeCollectionCreationFee',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_updateFee', internalType: 'uint256', type: 'uint256' }],
    name: 'changeCollectionUpdateFee',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_creationFee', internalType: 'uint256', type: 'uint256' }
    ],
    name: 'changeDocumentCreationFee',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_updateFee', internalType: 'uint256', type: 'uint256' }],
    name: 'changeDocumentUpdateFee',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {
        name: '_feeCollectorAddress',
        internalType: 'address payable',
        type: 'address'
      }
    ],
    name: 'changeFeeCollectorAddress',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_creationFee', internalType: 'uint256', type: 'uint256' }
    ],
    name: 'changeOrgCreationFee',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_updateFee', internalType: 'uint256', type: 'uint256' }],
    name: 'changeOrgUpdateFee',
    outputs: []
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'collectionCreationFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'address', type: 'address' }
    ],
    name: 'collectionPublishers',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'collectionUpdateFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_organisationId', internalType: 'uint256', type: 'uint256' },
      { name: '_collectionName', internalType: 'string', type: 'string' },
      {
        name: '_collectionInfoFields',
        internalType: 'string[]',
        type: 'string[]'
      },
      {
        name: '_collectionInfoDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]'
      },
      {
        name: '_collectionInfoValues',
        internalType: 'string[]',
        type: 'string[]'
      },
      { name: '_fieldNames', internalType: 'string[]', type: 'string[]' },
      { name: '_fieldDataTypes', internalType: 'uint256[]', type: 'uint256[]' }
    ],
    name: 'createCollection',
    outputs: []
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_organisationName', internalType: 'string', type: 'string' },
      {
        name: '_organisationInfoFields',
        internalType: 'string[]',
        type: 'string[]'
      },
      {
        name: '_organisationInfoDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]'
      },
      {
        name: '_organisationInfoValues',
        internalType: 'string[]',
        type: 'string[]'
      }
    ],
    name: 'createOrganisation',
    outputs: [
      { name: 'organisationId', internalType: 'uint256', type: 'uint256' }
    ]
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_organisationName', internalType: 'string', type: 'string' },
      {
        name: '_organisationInfoFields',
        internalType: 'string[]',
        type: 'string[]'
      },
      {
        name: '_organisationInfoDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]'
      },
      {
        name: '_organisationInfoValues',
        internalType: 'string[]',
        type: 'string[]'
      },
      { name: '_collectionName', internalType: 'string', type: 'string' },
      {
        name: '_collectionInfoFields',
        internalType: 'string[]',
        type: 'string[]'
      },
      {
        name: '_collectionInfoDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]'
      },
      {
        name: '_collectionInfoValues',
        internalType: 'string[]',
        type: 'string[]'
      },
      { name: '_fieldNames', internalType: 'string[]', type: 'string[]' },
      { name: '_fieldDataTypes', internalType: 'uint256[]', type: 'uint256[]' }
    ],
    name: 'createOrganisationAndCollection',
    outputs: []
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'docCreationFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'documentUpdateFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'feeCollectorAddress',
    outputs: [{ name: '', internalType: 'address payable', type: 'address' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getFees',
    outputs: [
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'uint256', type: 'uint256' }
    ]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'organisationId', internalType: 'uint256', type: 'uint256' },
      { name: 'collectionId', internalType: 'uint256', type: 'uint256' },
      { name: 'user', internalType: 'address', type: 'address' }
    ],
    name: 'isCollectionPublisher',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'organisationId', internalType: 'uint256', type: 'uint256' },
      { name: 'collectionId', internalType: 'uint256', type: 'uint256' },
      { name: 'documentId', internalType: 'uint256', type: 'uint256' },
      { name: 'user', internalType: 'address', type: 'address' }
    ],
    name: 'isDocumentUpdator',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'organisationId', internalType: 'uint256', type: 'uint256' },
      { name: 'user', internalType: 'address', type: 'address' }
    ],
    name: 'isOrgAdmin',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint256', type: 'uint256' },
      { name: '', internalType: 'address', type: 'address' }
    ],
    name: 'orgAdmins',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'orgCreationFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'orgUpdateFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }]
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }]
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_organisationId', internalType: 'uint256', type: 'uint256' },
      { name: '_collectionId', internalType: 'uint256', type: 'uint256' },
      { name: '_fieldNames', internalType: 'string[]', type: 'string[]' },
      { name: '_fieldDataTypes', internalType: 'uint256[]', type: 'uint256[]' },
      { name: '_fieldValues', internalType: 'string[]', type: 'string[]' }
    ],
    name: 'publishDocument',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: []
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_organisationId', internalType: 'uint256', type: 'uint256' },
      { name: '_collectionId', internalType: 'uint256', type: 'uint256' },
      { name: '_collectionName', internalType: 'string', type: 'string' },
      {
        name: '_collectionInfoFields',
        internalType: 'string[]',
        type: 'string[]'
      },
      {
        name: '_collectionInfoDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]'
      },
      {
        name: '_collectionInfoValues',
        internalType: 'string[]',
        type: 'string[]'
      },
      { name: '_fieldNames', internalType: 'string[]', type: 'string[]' },
      { name: '_fieldDataTypes', internalType: 'uint256[]', type: 'uint256[]' },
      { name: '_retired', internalType: 'bool', type: 'bool' }
    ],
    name: 'updateCollection',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'organisationId', internalType: 'uint256', type: 'uint256' },
      { name: 'collectionId', internalType: 'uint256', type: 'uint256' },
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'status', internalType: 'bool', type: 'bool' }
    ],
    name: 'updateCollectionPublishers',
    outputs: []
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_organisationId', internalType: 'uint256', type: 'uint256' },
      { name: '_collectionId', internalType: 'uint256', type: 'uint256' },
      { name: '_documentId', internalType: 'uint256', type: 'uint256' },
      { name: '_fieldNames', internalType: 'string[]', type: 'string[]' },
      { name: '_fieldDataTypes', internalType: 'uint256[]', type: 'uint256[]' },
      { name: '_fieldValues', internalType: 'string[]', type: 'string[]' },
      { name: '_retired', internalType: 'bool', type: 'bool' }
    ],
    name: 'updateDocument',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'organisationId', internalType: 'uint256', type: 'uint256' },
      { name: 'collectionId', internalType: 'uint256', type: 'uint256' },
      { name: 'documentId', internalType: 'uint256', type: 'uint256' },
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'status', internalType: 'bool', type: 'bool' }
    ],
    name: 'updateDocumentUpdatorRole',
    outputs: []
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'organisationId', internalType: 'uint256', type: 'uint256' },
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'status', internalType: 'bool', type: 'bool' }
    ],
    name: 'updateOrgAdminRole',
    outputs: []
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: '_organisationId', internalType: 'uint256', type: 'uint256' },
      { name: '_organisationName', internalType: 'string', type: 'string' },
      {
        name: '_organisationInfoFields',
        internalType: 'string[]',
        type: 'string[]'
      },
      {
        name: '_organisationInfoDataTypes',
        internalType: 'uint256[]',
        type: 'uint256[]'
      },
      {
        name: '_organisationInfoValues',
        internalType: 'string[]',
        type: 'string[]'
      },
      { name: '_retired', internalType: 'bool', type: 'bool' }
    ],
    name: 'updateOrganisation',
    outputs: []
  }
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__.
 */
export function useDatabaseRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"collectionCreationFee"`.
 */
export function useDatabaseCollectionCreationFee<
  TFunctionName extends 'collectionCreationFee',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'collectionCreationFee',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"collectionPublishers"`.
 */
export function useDatabaseCollectionPublishers<
  TFunctionName extends 'collectionPublishers',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'collectionPublishers',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"collectionUpdateFee"`.
 */
export function useDatabaseCollectionUpdateFee<
  TFunctionName extends 'collectionUpdateFee',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'collectionUpdateFee',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"docCreationFee"`.
 */
export function useDatabaseDocCreationFee<
  TFunctionName extends 'docCreationFee',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'docCreationFee',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"documentUpdateFee"`.
 */
export function useDatabaseDocumentUpdateFee<
  TFunctionName extends 'documentUpdateFee',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'documentUpdateFee',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"feeCollectorAddress"`.
 */
export function useDatabaseFeeCollectorAddress<
  TFunctionName extends 'feeCollectorAddress',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'feeCollectorAddress',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"getFees"`.
 */
export function useDatabaseGetFees<
  TFunctionName extends 'getFees',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'getFees',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"isCollectionPublisher"`.
 */
export function useDatabaseIsCollectionPublisher<
  TFunctionName extends 'isCollectionPublisher',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'isCollectionPublisher',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"isDocumentUpdator"`.
 */
export function useDatabaseIsDocumentUpdator<
  TFunctionName extends 'isDocumentUpdator',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'isDocumentUpdator',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"isOrgAdmin"`.
 */
export function useDatabaseIsOrgAdmin<
  TFunctionName extends 'isOrgAdmin',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'isOrgAdmin',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"orgAdmins"`.
 */
export function useDatabaseOrgAdmins<
  TFunctionName extends 'orgAdmins',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'orgAdmins',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"orgCreationFee"`.
 */
export function useDatabaseOrgCreationFee<
  TFunctionName extends 'orgCreationFee',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'orgCreationFee',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"orgUpdateFee"`.
 */
export function useDatabaseOrgUpdateFee<
  TFunctionName extends 'orgUpdateFee',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'orgUpdateFee',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"owner"`.
 */
export function useDatabaseOwner<
  TFunctionName extends 'owner',
  TSelectData = ReadContractResult<typeof databaseABI, TFunctionName>
>(
  config: Omit<
    UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any
) {
  return useContractRead({
    abi: databaseABI,
    functionName: 'owner',
    ...config
  } as UseContractReadConfig<typeof databaseABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__.
 */
export function useDatabaseWrite<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          string
        >['request']['abi'],
        TFunctionName,
        TMode
      >
    : UseContractWriteConfig<typeof databaseABI, TFunctionName, TMode> & {
        abi?: never
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, TFunctionName, TMode>({
    abi: databaseABI,
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeCollectionCreationFee"`.
 */
export function useDatabaseChangeCollectionCreationFee<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'changeCollectionCreationFee'
        >['request']['abi'],
        'changeCollectionCreationFee',
        TMode
      > & { functionName?: 'changeCollectionCreationFee' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'changeCollectionCreationFee',
        TMode
      > & {
        abi?: never
        functionName?: 'changeCollectionCreationFee'
      } = {} as any
) {
  return useContractWrite<
    typeof databaseABI,
    'changeCollectionCreationFee',
    TMode
  >({
    abi: databaseABI,
    functionName: 'changeCollectionCreationFee',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeCollectionUpdateFee"`.
 */
export function useDatabaseChangeCollectionUpdateFee<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'changeCollectionUpdateFee'
        >['request']['abi'],
        'changeCollectionUpdateFee',
        TMode
      > & { functionName?: 'changeCollectionUpdateFee' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'changeCollectionUpdateFee',
        TMode
      > & {
        abi?: never
        functionName?: 'changeCollectionUpdateFee'
      } = {} as any
) {
  return useContractWrite<
    typeof databaseABI,
    'changeCollectionUpdateFee',
    TMode
  >({
    abi: databaseABI,
    functionName: 'changeCollectionUpdateFee',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeDocumentCreationFee"`.
 */
export function useDatabaseChangeDocumentCreationFee<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'changeDocumentCreationFee'
        >['request']['abi'],
        'changeDocumentCreationFee',
        TMode
      > & { functionName?: 'changeDocumentCreationFee' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'changeDocumentCreationFee',
        TMode
      > & {
        abi?: never
        functionName?: 'changeDocumentCreationFee'
      } = {} as any
) {
  return useContractWrite<
    typeof databaseABI,
    'changeDocumentCreationFee',
    TMode
  >({
    abi: databaseABI,
    functionName: 'changeDocumentCreationFee',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeDocumentUpdateFee"`.
 */
export function useDatabaseChangeDocumentUpdateFee<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'changeDocumentUpdateFee'
        >['request']['abi'],
        'changeDocumentUpdateFee',
        TMode
      > & { functionName?: 'changeDocumentUpdateFee' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'changeDocumentUpdateFee',
        TMode
      > & {
        abi?: never
        functionName?: 'changeDocumentUpdateFee'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'changeDocumentUpdateFee', TMode>(
    {
      abi: databaseABI,
      functionName: 'changeDocumentUpdateFee',
      ...config
    } as any
  )
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeFeeCollectorAddress"`.
 */
export function useDatabaseChangeFeeCollectorAddress<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'changeFeeCollectorAddress'
        >['request']['abi'],
        'changeFeeCollectorAddress',
        TMode
      > & { functionName?: 'changeFeeCollectorAddress' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'changeFeeCollectorAddress',
        TMode
      > & {
        abi?: never
        functionName?: 'changeFeeCollectorAddress'
      } = {} as any
) {
  return useContractWrite<
    typeof databaseABI,
    'changeFeeCollectorAddress',
    TMode
  >({
    abi: databaseABI,
    functionName: 'changeFeeCollectorAddress',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeOrgCreationFee"`.
 */
export function useDatabaseChangeOrgCreationFee<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'changeOrgCreationFee'
        >['request']['abi'],
        'changeOrgCreationFee',
        TMode
      > & { functionName?: 'changeOrgCreationFee' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'changeOrgCreationFee',
        TMode
      > & {
        abi?: never
        functionName?: 'changeOrgCreationFee'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'changeOrgCreationFee', TMode>({
    abi: databaseABI,
    functionName: 'changeOrgCreationFee',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeOrgUpdateFee"`.
 */
export function useDatabaseChangeOrgUpdateFee<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'changeOrgUpdateFee'
        >['request']['abi'],
        'changeOrgUpdateFee',
        TMode
      > & { functionName?: 'changeOrgUpdateFee' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'changeOrgUpdateFee',
        TMode
      > & {
        abi?: never
        functionName?: 'changeOrgUpdateFee'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'changeOrgUpdateFee', TMode>({
    abi: databaseABI,
    functionName: 'changeOrgUpdateFee',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"createCollection"`.
 */
export function useDatabaseCreateCollection<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'createCollection'
        >['request']['abi'],
        'createCollection',
        TMode
      > & { functionName?: 'createCollection' }
    : UseContractWriteConfig<typeof databaseABI, 'createCollection', TMode> & {
        abi?: never
        functionName?: 'createCollection'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'createCollection', TMode>({
    abi: databaseABI,
    functionName: 'createCollection',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"createOrganisation"`.
 */
export function useDatabaseCreateOrganisation<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'createOrganisation'
        >['request']['abi'],
        'createOrganisation',
        TMode
      > & { functionName?: 'createOrganisation' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'createOrganisation',
        TMode
      > & {
        abi?: never
        functionName?: 'createOrganisation'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'createOrganisation', TMode>({
    abi: databaseABI,
    functionName: 'createOrganisation',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"createOrganisationAndCollection"`.
 */
export function useDatabaseCreateOrganisationAndCollection<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'createOrganisationAndCollection'
        >['request']['abi'],
        'createOrganisationAndCollection',
        TMode
      > & { functionName?: 'createOrganisationAndCollection' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'createOrganisationAndCollection',
        TMode
      > & {
        abi?: never
        functionName?: 'createOrganisationAndCollection'
      } = {} as any
) {
  return useContractWrite<
    typeof databaseABI,
    'createOrganisationAndCollection',
    TMode
  >({
    abi: databaseABI,
    functionName: 'createOrganisationAndCollection',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"publishDocument"`.
 */
export function useDatabasePublishDocument<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'publishDocument'
        >['request']['abi'],
        'publishDocument',
        TMode
      > & { functionName?: 'publishDocument' }
    : UseContractWriteConfig<typeof databaseABI, 'publishDocument', TMode> & {
        abi?: never
        functionName?: 'publishDocument'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'publishDocument', TMode>({
    abi: databaseABI,
    functionName: 'publishDocument',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"renounceOwnership"`.
 */
export function useDatabaseRenounceOwnership<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'renounceOwnership'
        >['request']['abi'],
        'renounceOwnership',
        TMode
      > & { functionName?: 'renounceOwnership' }
    : UseContractWriteConfig<typeof databaseABI, 'renounceOwnership', TMode> & {
        abi?: never
        functionName?: 'renounceOwnership'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'renounceOwnership', TMode>({
    abi: databaseABI,
    functionName: 'renounceOwnership',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"transferOwnership"`.
 */
export function useDatabaseTransferOwnership<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'transferOwnership'
        >['request']['abi'],
        'transferOwnership',
        TMode
      > & { functionName?: 'transferOwnership' }
    : UseContractWriteConfig<typeof databaseABI, 'transferOwnership', TMode> & {
        abi?: never
        functionName?: 'transferOwnership'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'transferOwnership', TMode>({
    abi: databaseABI,
    functionName: 'transferOwnership',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateCollection"`.
 */
export function useDatabaseUpdateCollection<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'updateCollection'
        >['request']['abi'],
        'updateCollection',
        TMode
      > & { functionName?: 'updateCollection' }
    : UseContractWriteConfig<typeof databaseABI, 'updateCollection', TMode> & {
        abi?: never
        functionName?: 'updateCollection'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'updateCollection', TMode>({
    abi: databaseABI,
    functionName: 'updateCollection',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateCollectionPublishers"`.
 */
export function useDatabaseUpdateCollectionPublishers<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'updateCollectionPublishers'
        >['request']['abi'],
        'updateCollectionPublishers',
        TMode
      > & { functionName?: 'updateCollectionPublishers' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'updateCollectionPublishers',
        TMode
      > & {
        abi?: never
        functionName?: 'updateCollectionPublishers'
      } = {} as any
) {
  return useContractWrite<
    typeof databaseABI,
    'updateCollectionPublishers',
    TMode
  >({
    abi: databaseABI,
    functionName: 'updateCollectionPublishers',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateDocument"`.
 */
export function useDatabaseUpdateDocument<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'updateDocument'
        >['request']['abi'],
        'updateDocument',
        TMode
      > & { functionName?: 'updateDocument' }
    : UseContractWriteConfig<typeof databaseABI, 'updateDocument', TMode> & {
        abi?: never
        functionName?: 'updateDocument'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'updateDocument', TMode>({
    abi: databaseABI,
    functionName: 'updateDocument',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateDocumentUpdatorRole"`.
 */
export function useDatabaseUpdateDocumentUpdatorRole<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'updateDocumentUpdatorRole'
        >['request']['abi'],
        'updateDocumentUpdatorRole',
        TMode
      > & { functionName?: 'updateDocumentUpdatorRole' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'updateDocumentUpdatorRole',
        TMode
      > & {
        abi?: never
        functionName?: 'updateDocumentUpdatorRole'
      } = {} as any
) {
  return useContractWrite<
    typeof databaseABI,
    'updateDocumentUpdatorRole',
    TMode
  >({
    abi: databaseABI,
    functionName: 'updateDocumentUpdatorRole',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateOrgAdminRole"`.
 */
export function useDatabaseUpdateOrgAdminRole<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'updateOrgAdminRole'
        >['request']['abi'],
        'updateOrgAdminRole',
        TMode
      > & { functionName?: 'updateOrgAdminRole' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'updateOrgAdminRole',
        TMode
      > & {
        abi?: never
        functionName?: 'updateOrgAdminRole'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'updateOrgAdminRole', TMode>({
    abi: databaseABI,
    functionName: 'updateOrgAdminRole',
    ...config
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateOrganisation"`.
 */
export function useDatabaseUpdateOrganisation<
  TMode extends WriteContractMode = undefined
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof databaseABI,
          'updateOrganisation'
        >['request']['abi'],
        'updateOrganisation',
        TMode
      > & { functionName?: 'updateOrganisation' }
    : UseContractWriteConfig<
        typeof databaseABI,
        'updateOrganisation',
        TMode
      > & {
        abi?: never
        functionName?: 'updateOrganisation'
      } = {} as any
) {
  return useContractWrite<typeof databaseABI, 'updateOrganisation', TMode>({
    abi: databaseABI,
    functionName: 'updateOrganisation',
    ...config
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__.
 */
export function usePrepareDatabaseWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, TFunctionName>,
    'abi'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeCollectionCreationFee"`.
 */
export function usePrepareDatabaseChangeCollectionCreationFee(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof databaseABI,
      'changeCollectionCreationFee'
    >,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'changeCollectionCreationFee',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'changeCollectionCreationFee'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeCollectionUpdateFee"`.
 */
export function usePrepareDatabaseChangeCollectionUpdateFee(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof databaseABI,
      'changeCollectionUpdateFee'
    >,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'changeCollectionUpdateFee',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'changeCollectionUpdateFee'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeDocumentCreationFee"`.
 */
export function usePrepareDatabaseChangeDocumentCreationFee(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof databaseABI,
      'changeDocumentCreationFee'
    >,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'changeDocumentCreationFee',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'changeDocumentCreationFee'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeDocumentUpdateFee"`.
 */
export function usePrepareDatabaseChangeDocumentUpdateFee(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof databaseABI,
      'changeDocumentUpdateFee'
    >,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'changeDocumentUpdateFee',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'changeDocumentUpdateFee'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeFeeCollectorAddress"`.
 */
export function usePrepareDatabaseChangeFeeCollectorAddress(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof databaseABI,
      'changeFeeCollectorAddress'
    >,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'changeFeeCollectorAddress',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'changeFeeCollectorAddress'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeOrgCreationFee"`.
 */
export function usePrepareDatabaseChangeOrgCreationFee(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'changeOrgCreationFee'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'changeOrgCreationFee',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'changeOrgCreationFee'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"changeOrgUpdateFee"`.
 */
export function usePrepareDatabaseChangeOrgUpdateFee(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'changeOrgUpdateFee'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'changeOrgUpdateFee',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'changeOrgUpdateFee'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"createCollection"`.
 */
export function usePrepareDatabaseCreateCollection(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'createCollection'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'createCollection',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'createCollection'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"createOrganisation"`.
 */
export function usePrepareDatabaseCreateOrganisation(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'createOrganisation'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'createOrganisation',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'createOrganisation'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"createOrganisationAndCollection"`.
 */
export function usePrepareDatabaseCreateOrganisationAndCollection(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof databaseABI,
      'createOrganisationAndCollection'
    >,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'createOrganisationAndCollection',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'createOrganisationAndCollection'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"publishDocument"`.
 */
export function usePrepareDatabasePublishDocument(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'publishDocument'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'publishDocument',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'publishDocument'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"renounceOwnership"`.
 */
export function usePrepareDatabaseRenounceOwnership(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'renounceOwnership'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'renounceOwnership',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'renounceOwnership'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"transferOwnership"`.
 */
export function usePrepareDatabaseTransferOwnership(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'transferOwnership'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'transferOwnership',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'transferOwnership'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateCollection"`.
 */
export function usePrepareDatabaseUpdateCollection(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'updateCollection'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'updateCollection',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'updateCollection'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateCollectionPublishers"`.
 */
export function usePrepareDatabaseUpdateCollectionPublishers(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof databaseABI,
      'updateCollectionPublishers'
    >,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'updateCollectionPublishers',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'updateCollectionPublishers'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateDocument"`.
 */
export function usePrepareDatabaseUpdateDocument(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'updateDocument'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'updateDocument',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'updateDocument'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateDocumentUpdatorRole"`.
 */
export function usePrepareDatabaseUpdateDocumentUpdatorRole(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof databaseABI,
      'updateDocumentUpdatorRole'
    >,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'updateDocumentUpdatorRole',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'updateDocumentUpdatorRole'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateOrgAdminRole"`.
 */
export function usePrepareDatabaseUpdateOrgAdminRole(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'updateOrgAdminRole'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'updateOrgAdminRole',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'updateOrgAdminRole'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link databaseABI}__ and `functionName` set to `"updateOrganisation"`.
 */
export function usePrepareDatabaseUpdateOrganisation(
  config: Omit<
    UsePrepareContractWriteConfig<typeof databaseABI, 'updateOrganisation'>,
    'abi' | 'functionName'
  > = {} as any
) {
  return usePrepareContractWrite({
    abi: databaseABI,
    functionName: 'updateOrganisation',
    ...config
  } as UsePrepareContractWriteConfig<typeof databaseABI, 'updateOrganisation'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__.
 */
export function useDatabaseEvent<TEventName extends string>(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, TEventName>,
    'abi'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    ...config
  } as UseContractEventConfig<typeof databaseABI, TEventName>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"CollectionCreated"`.
 */
export function useDatabaseCollectionCreatedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'CollectionCreated'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'CollectionCreated',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'CollectionCreated'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"CollectionUpdated"`.
 */
export function useDatabaseCollectionUpdatedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'CollectionUpdated'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'CollectionUpdated',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'CollectionUpdated'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"DocumentPublished"`.
 */
export function useDatabaseDocumentPublishedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'DocumentPublished'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'DocumentPublished',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'DocumentPublished'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"DocumentUpdated"`.
 */
export function useDatabaseDocumentUpdatedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'DocumentUpdated'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'DocumentUpdated',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'DocumentUpdated'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"FeeCollectorAddressUpdated"`.
 */
export function useDatabaseFeeCollectorAddressUpdatedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'FeeCollectorAddressUpdated'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'FeeCollectorAddressUpdated',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'FeeCollectorAddressUpdated'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"OrganisationCreated"`.
 */
export function useDatabaseOrganisationCreatedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'OrganisationCreated'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'OrganisationCreated',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'OrganisationCreated'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"OrganisationUpdated"`.
 */
export function useDatabaseOrganisationUpdatedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'OrganisationUpdated'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'OrganisationUpdated',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'OrganisationUpdated'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"OwnershipTransferred"`.
 */
export function useDatabaseOwnershipTransferredEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'OwnershipTransferred'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'OwnershipTransferred',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'OwnershipTransferred'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"collectionCreationFeeChanged"`.
 */
export function useDatabaseCollectionCreationFeeChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'collectionCreationFeeChanged'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'collectionCreationFeeChanged',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'collectionCreationFeeChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"collectionPublisherChanged"`.
 */
export function useDatabaseCollectionPublisherChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'collectionPublisherChanged'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'collectionPublisherChanged',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'collectionPublisherChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"collectionUpdateFeeChanged"`.
 */
export function useDatabaseCollectionUpdateFeeChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'collectionUpdateFeeChanged'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'collectionUpdateFeeChanged',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'collectionUpdateFeeChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"documentCreationFeeChanged"`.
 */
export function useDatabaseDocumentCreationFeeChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'documentCreationFeeChanged'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'documentCreationFeeChanged',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'documentCreationFeeChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"documentUpdateFeeChanged"`.
 */
export function useDatabaseDocumentUpdateFeeChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'documentUpdateFeeChanged'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'documentUpdateFeeChanged',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'documentUpdateFeeChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"documentUpdatorChanged"`.
 */
export function useDatabaseDocumentUpdatorChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'documentUpdatorChanged'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'documentUpdatorChanged',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'documentUpdatorChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"orgAdminChanged"`.
 */
export function useDatabaseOrgAdminChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'orgAdminChanged'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'orgAdminChanged',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'orgAdminChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"orgCreationFeeChanged"`.
 */
export function useDatabaseOrgCreationFeeChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'orgCreationFeeChanged'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'orgCreationFeeChanged',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'orgCreationFeeChanged'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link databaseABI}__ and `eventName` set to `"orgUpdateFeeChanged"`.
 */
export function useDatabaseOrgUpdateFeeChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof databaseABI, 'orgUpdateFeeChanged'>,
    'abi' | 'eventName'
  > = {} as any
) {
  return useContractEvent({
    abi: databaseABI,
    eventName: 'orgUpdateFeeChanged',
    ...config
  } as UseContractEventConfig<typeof databaseABI, 'orgUpdateFeeChanged'>)
}
